import './globals.css';
import { Inter } from 'next/font/google';
import Header from '../components/Headers/Header';
import Providers from './theme-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={`transition duration-300 ${inter.className}`}>
      <body className='flex flex-col min-h-screen'>
        <Providers>
          <Header />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
